<?php

namespace App\Http\Requests\FormRequestToAPI;

use Illuminate\Foundation\Http\FormRequest;

class FormRequestToAPI extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }


    /**
     * Esquematizacion de respuestas para API
     *
     * @param array $errors
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function response(array $errors)
    {
        //return parent::response($errors); // TODO: Change the autogenerated stub
        return response()->json(['error' => trans('errors.400'),'message' => trans('errors.901'), 'campsFailed' => $errors], 400);
    }
}
